FROM dohuuhung1234/dohuuhung1234:ubuntu_1604

LABEL maintainer="Ubuntu16.04 Docker Maintainers dohuuhung1234@gmail.com"

# Install requirement packages
RUN apt-get update \
    && apt install -y systemd

CMD ["tail", "-f", "/dev/null"]
